/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Registration = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'confirmed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], []),
  'getRemainingSeats' : IDL.Func([], [IDL.Nat], ['query']),
  'isEmailRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Registration = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'confirmed' : IDL.Bool,
  });
  
  return IDL.Service({
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], []),
    'getRemainingSeats' : IDL.Func([], [IDL.Nat], ['query']),
    'isEmailRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };